For safety reasons, use synchronous API.
With TomCat 9.0.31-1~deb10u6 asynchonous communication often fails with
an exception:

java.lang.IllegalStateException: The remote endpoint was in state
[TEXT_FULL_WRITING] which is an invalid state for called method
  at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.checkState(WsRemoteEndpointImplBase.java:1234)
  at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.textStart(WsRemoteEndpointImplBase.java:1196)
  at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendStringByCompletion(WsRemoteEndpointImplBase.java:209)
  at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendStringByFuture(WsRemoteEndpointImplBase.java:197)
  at org.apache.tomcat.websocket.WsRemoteEndpointAsync.sendText(WsRemoteEndpointAsync.java:53)
  at de.haumacher.wizard.server.servlet.WizardEndpoint.lambda$onOpen$0(WizardEndpoint.java:61)
  at de.haumacher.wizard.server.ClientHandler.sendMessage(ClientHandler.java:168)
  at de.haumacher.wizard.server.GameClientImpl.sendMessage(GameClientImpl.java:48)
  at de.haumacher.wizard.logic.WizardGame.broadCast(WizardGame.java:202)
  at de.haumacher.wizard.logic.WizardGame.requestNextBid(WizardGame.java:322)
  at de.haumacher.wizard.logic.WizardGame.visit(WizardGame.java:415)
  at de.haumacher.wizard.logic.WizardGame.visit(WizardGame.java:55)